title: Curriculum Theme
description: Theme for Deep Dive Coding Java + Android Bootcamp curricular content hosted on GitHub Pages.
author:
  name: Nick Bennett
  email: nick@nickbenn.com

# The following options are shown with their default values.

repository_link:
  enabled: true # Set this to false if repository link is not wanted on a public repository.

heading_navigator:
  enabled: true # Set this to false if intra-page navigator is not wanted.

page_navigator:
  enabled: true # Set this to false if an inter-page navigator is not wanted.

google_analytics: # Tracking ID, e.g. "UA-000000-01"; ignore if Google Analytics not needed.
