title: Curriculum Theme
description: Theme for Deep Dive Coding Java + Android Bootcamp curricular content hosted on GitHub Pages.
icon: /assets/images/ddc.png
favicon: /assets/images/favicon.ico

show_downloads: true # This setting is ignored if the repository is private.

heading_navigator: true # Set this to false if intra-page navigator is not wanted. 

page_navigator: true # Set this to true if an inter-page navigator bar is wanted.

titles_from_headings:
  enabled: false # We recommend leaving this setting disabled in this theme.
  
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # Pages use _layouts/default.html, unless set in page front matter.
      
google_analytics: # Tracking ID, e.g. "UA-000000-01"; ignore if Google Analytics not needed.

